# Generated by Django 4.0 on 2021-12-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('cin', models.PositiveBigIntegerField()),
                ('securite_sociale', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('is_admin', models.BooleanField(default=True)),
                ('is_intern', models.BooleanField(default=True)),
                ('contract', models.CharField(choices=[('CDD', 'CDD'), ('CDI', 'CDI'), ('Stage', 'Stage'), ('Alternance', 'Alternance')], default='CDI', max_length=20)),
                ('phone', models.BigIntegerField()),
                ('salary', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
    ]
